### ISSUE TITLE
Display time and link type on hover

### ISSUE THREAD

**Issue by kam56** [ItJustWorksBetterTM/EiffelVis#4]
#4 As a user I want to see information related to a chosen node in order to get a visual representation of what event I’m looking at.

**Acceptance Criteria**

- [x] Performance is not impacted
- [x] Popup is displayed on hover
- [x] Information displayed: - Link type   - Time (human readable)
- [x] Modify the data model to add link type
- [x] Comment code

**Comment by RuthgerD** [comment]
Currently you get event meta data on event click as this data has to be fetched through a GET request, on hover might trigger to many requests; at the very least there would need to be a delay for the hover.

**Comment by alrapal** [comment]
> Currently you get event meta data on event click as this data has to be fetched through a GET request, on hover might trigger to many requests; at the very least there would need to be a delay for the hover.

Hello Ruthger! Nice to see you here 😄 
Thanks for your insights on this! 

The issues we had on Github at the time you commented were not completely finalised. I update this one to its latest version so it reflect what we actually want to achieve. We will update the rest of them next week. 

The information we want to display is the time attached to the node and the type of links it has. 
For the time, we do not need to query the BE since the node itself contains the flat event with some information like the type, the time and the ID for instance. But when it comes to the link type, this might be a bit trickier. 

2 solutions so far, querying the back end and have a delay before hovering to avoid overloading requests as you mentioned, or modify the BE so the cause is stored in the edge in the graph and we can use it directly from the node / edge without querying the BE. (The second one needs to be further investigated, not even sure it is possible to have that type of info stored in the edges but we will see!) If you have any insights, don't hesitate of course! We will continue working on this 

Thanks for you insights again!

**Comment by RuthgerD** [comment]
Ok I understand,
The backend already stores the link types, so that's not a worry.
the easiest way to do it would be to modify the `LeanEvent` type to also include the link types along with the target uuids;
This will impact event throughput to the frontend as link types are stored as strings. ([but is very easy](https://github.com/ItJustWorksTM/EiffelVis/blob/master/backend/crates/eiffelvis_core/src/domain/types.rs#L47))

To fix the throughput issue we could maintain a Event / Link type index on the backend to give these types an integer id instead, but that's a bit complex.

I do think just querying for the full event info will get you pretty far, but sending all link types will unlock some more use cases as well; maybe do some benchmarking for both cases and see what the user will want to use.
